### ISSUE TITLE
Suggestion: Add `prototype` to `CollectionFlowLayoutSizingStrategy.SizingMode.automatic`

### ISSUE THREAD

**Issue by JosephDuffy** [composed-swift/ComposedLayouts#1]
Only `CollectionFlowLayoutSizingStrategy.SizingMode.automatic` uses the prototype, and it is required when using `automatic`.

Updating `automatic` to `case automatic(isUniform: Bool, prototype: UICollectionReusableView)` would remove the check (and subsequent `fatalError`) and make the API clearer.

This is a breaking change and would require a new major version.

**Comment by shaps80** [comment]
So I would consider a rename (still a breaking change) but the reason I didn't do it that way in the end was because I gained type inference and consistency at the calcite when returning a `CollectionSection`.

The `DequeueMethod` provides the type and doesn't depend on FlowLayout thus SizingStrategies. Thoughts?

**Comment by JosephDuffy** [comment]
> So I would consider a rename (still a breaking change) but the reason I didn't do it that way in the end was because I gained type inference and consistency at the calcite when returning a `CollectionSection`.
> 
> The `DequeueMethod` provides the type and doesn't depend on FlowLayout thus SizingStrategies. Thoughts?

I'm not entirely sure what you mean. Nothing in this project returns a `CollectionSection` and `ComposedUI` doesn't rely on `ComposedLayouts`.

Is there another project that uses both these where this is an advantage?

**Comment by shaps80** [comment]
No, no, what I mean is – ComposedUI is used to return a `CollectionSection` and at the call-site you return a `DequeueMethod` which specifies the type for the cell already.

By adding it here as well, would mean the API consumer would have to specify the type twice, plus there would be no way (that I can tell) to ensure the 2 types match.

I don't see how this would work to be honest?

**Comment by JosephDuffy** [comment]
I understand what you're saying now but I can't find the issue. I tried making this change and working with the demo and it didn't cause any issues so I'm guessing the demo doesn't use this part of the API anywhere. Can you point to where the problem would be?

https://github.com/JosephDuffy/ComposedLayouts/commit/7d46db56eab4ab88fc39e92747d1dbbb08998263
https://github.com/JosephDuffy/ComposedMediaUI/commit/8c408d12b663374e87bf01828ea4336bb36b5528
https://github.com/JosephDuffy/Composed-Demo/commit/b7c016ece242f74234d09951f678a31d1dddec20

**Comment by shaps80** [comment]
This is a complex conversation, perhaps we could have a call sometime to discuss it a little more? Personally I'm not a fan of this but its possible I'm misunderstanding something so I'd love to hear it in more detail if you have time sometime this week?

**Comment by shaps80** [comment]
Hey @JosephDuffy so I misunderstood what this was doing. I've implemented this now and done a release including the changes from your fork. You can see the code in 1.0.2

**Comment by JosephDuffy** [comment]
> Hey @JosephDuffy so I misunderstood what this was doing. I've implemented this now and done a release including the changes from your fork. You can see the code in 1.0.2

Good stuff 👍
